# These are supported funding model platforms

github: elf-mouse
open_collective: balmjs
patreon: balmjs
issuehunt: balmjs/balm-ui
custom:
  [
    'https://material.balmjs.com/#/donate',
    'https://www.buymeacoffee.com/balmjs'
  ]
