# These are supported funding model platforms

patreon: balmjs
open_collective: balmjs
issuehunt: balmjs/balm-ui
custom: ["https://material.balmjs.com/#/donate", "https://www.buymeacoffee.com/balmjs"]
